from .device import get_device, DEVICE, DTYPE, to_torch, to_numpy
from .stats import compute_stats, compute_stats_streaming, compute_all_stats
from .methods import (
    m_rayleigh,
    m_mse,
    m_ray_mse,
    m_asym_rayleigh,
    m_asym_ray_mse,
    m_ray_asym_refine,
    m_ray_mse_asym_refine,
    m_ray_asym_refine_mse,
    m_ray_iterate,
    m_split_rank_ray,
    m_split_rank_ray_mse,
    m_split_rank_ray_iterate,
    m_uber,
    m_ray_contr_mse,
    m_ray_contr_mse_neg,
    m_resid_guided,
    m_uber_neg,
    m_uber_contr,
)
from .dispatch import generate_all_projections, generate_fast_projections, LazyProjectionDict
from .evaluation import evaluate_retrieval_fast, find_dim_range, evaluate_projections
from .datasets import load_askubuntu, load_twitter_url, load_quora, encode_texts, split_data
from .benchmark import DATASETS, MODELS, run_benchmark

__all__ = [
    "get_device",
    "DEVICE",
    "DTYPE",
    "to_torch",
    "to_numpy",
    "compute_stats",
    "compute_stats_streaming",
    "compute_all_stats",
    "m_rayleigh",
    "m_mse",
    "m_ray_mse",
    "m_asym_rayleigh",
    "m_asym_ray_mse",
    "m_ray_asym_refine",
    "m_ray_mse_asym_refine",
    "m_ray_asym_refine_mse",
    "m_ray_iterate",
    "m_split_rank_ray",
    "m_split_rank_ray_mse",
    "m_split_rank_ray_iterate",
    "m_uber",
    "m_ray_contr_mse",
    "m_ray_contr_mse_neg",
    "m_resid_guided",
    "m_uber_neg",
    "m_uber_contr",
    "generate_all_projections",
    "generate_fast_projections",
    "LazyProjectionDict",
    "evaluate_retrieval_fast",
    "find_dim_range",
    "evaluate_projections",
    "load_askubuntu",
    "load_twitter_url",
    "load_quora",
    "encode_texts",
    "split_data",
    "DATASETS",
    "MODELS",
    "run_benchmark",
]
